name: Trigger HL7 FHIR Autobuild
run-name: ${{ github.actor }} triggered a GitHub Action
on: 
  workflow_call: # Reusable by other workflows
  push:
  pull_request:
  workflow_dispatch:  
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.ref }} - ${{ github.repository }}"
      - run: | 
          curl --request POST \
          --header 'content-type: application/json' \
          --url https://us-central1-fhir-org-starter-project.cloudfunctions.net/ig-commit-trigger \
          --data '{"ref": "${{ github.ref }}", "repository": {"full_name": "${{ github.repository }}"}}'